--- 
redirects: 
  advanced/automated: ./library/advanced/automated.md
  advanced/grouping: ./library/advanced/grouping.md
  advanced/limits: ./library/advanced/limits.md
  advanced/resuming: ./library/advanced/resuming.md
  advanced/security: ./library/advanced/security.md
  alerts/slack: ./app/features/alerts.md
  api: ./library/api/README.md
  api/overview: ./library/api/README.md
  api/project: ./library/api/README.md
  api/run: ./library/api/README.md
  cli/overview: ./library/cli.md
  cli/restoring: ./library/cli.md
  docs/: ./README.md
  docs/advanced/automated: ./library/advanced/automated.md
  docs/advanced/grouping: ./library/advanced/grouping.md
  docs/advanced/limits: ./library/advanced/limits.md
  docs/advanced/resuming: ./library/advanced/resuming.md
  docs/advanced/security: ./library/advanced/security.md
  docs/alerts/slack: ./app/features/alerts.md
  docs/api: ./library/api/README.md
  docs/api/overview: ./library/api/README.md
  docs/api/project: ./library/api/README.md
  docs/api/run: ./library/api/README.md
  docs/artifacts: ./library/python/init.md
  docs/automated: ./library/advanced/automated.md
  docs/cli/overview: ./library/cli.md
  docs/cli/restoring: ./library/cli.md
  docs/config: ./library/python/config.md
  docs/enterprise: ./enterprise/overview.md
  docs/enterprise/about: ./enterprise/overview.md
  docs/enterprise/cloud: ./enterprise/cloud.md
  docs/enterprise/setup: ./enterprise/setup.md
  docs/enterprise/config: ./enterprise/configuration.md
  docs/enterprise/upgrades: ./enterprise/upgrades.md
  docs/enterprise/sending-data: ./enterprise/sending-data.md
  docs/examples: ./library/example-projects/README.md
  docs/faq: ./overview/company-faq.md
  docs/frameworks/catalyst: ./integrations/catalyst.md
  docs/frameworks/examples: ./examples.md
  docs/frameworks/fastai: ./integrations/fastai.md
  docs/frameworks/fastai-example: ./integrations/fastai/README.md
  docs/frameworks/jax-example: ./integrations/jax.md
  docs/frameworks/keras: ./integrations/keras.md
  docs/frameworks/keras-example: ./integrations/keras.md
  docs/frameworks/numpy-example: ./integrations/numpy.md
  docs/frameworks/pytorch: ./integrations/pytorch.md
  docs/frameworks/pytorch-example: ./integrations/pytorch.md
  docs/frameworks/scikit: ./integrations/scikit.md
  docs/frameworks/scikit-example: ./integrations/scikit.md
  docs/frameworks/tensorflow: ./integrations/tensorflow.md
  docs/frameworks/tensorflow-example: ./integrations/tensorflow.md
  docs/frameworks/xgboost: ./integrations/xgboost.md
  docs/frameworks/xgboost-example: ./integrations/xgboost.md
  docs/getting-started: ./quickstart.md
  docs/init: ./library/init.md
  docs/integrations/api: ./library/api/README.md
  ? "docs/integrations/api#special-methods"
  : ./library/api/README.md
  docs/integrations/databricks: ./integrations/databricks.md
  docs/integrations/docker: ./integrations/docker.md
  docs/integrations/jupyter: ./integrations/jupyter.md
  docs/integrations/kubeflow: ./integrations/kubeflow.md
  docs/integrations/ray: ./integrations/ray.md
  docs/integrations/sagemaker: ./integrations/sagemaker.md
  docs/integrations/tensorboard: ./integrations/tensorboard.md
  docs/log: ./library/python/log.md
  ? "docs/log#summary-metrics"
  : "./library/python/log#summary-metrics.md"
  docs/logs: ./library/python/log.md
  docs/overview/company-faq: ./overview/company-faq.md
  docs/overview/getting-help: ./overview/getting-help.md
  docs/overview/overview: ./overview.md
  docs/overview/technical-faq: ./overview/technical-faq.md
  docs/restore: ./library/python/restore.md
  docs/save: ./library/python/save.md
  docs/started: ./quickstart.md
  docs/sweeps/configuration: ./library/sweeps/configuration.md
  docs/sweeps/local: ./library/sweeps/local-controller.md
  docs/sweeps/overview: ./library/sweeps.md
  docs/sweeps/python: ./library/sweeps/python-api.md
  docs/wandb/config: ./library/python/config.md
  docs/wandb/init: ./library/python/init.md
  docs/wandb/log: ./library/python/log.md
  docs/wandb/restore: ./library/python/restore.md
  docs/wandb/save: ./library/python/save.md
  en/help: ./README.md
  examples: ./library/example-projects/README.md
  enterprise: ./enterprise/overview.md
  enterprise/about: ./enterprise/overview.md
  enterprise/cloud: ./enterprise/cloud.md
  enterprise/config: ./enterprise/configuration.md
  enterprise/setup: ./enterprise/setup.md
  enterprise/upgrades: ./enterprise/upgrades.md
  enterprise/sending-data: ./enterprise/sending-data.md
  frameworks/catalyst: ./integrations/catalyst.md
  frameworks/examples: ./examples.md
  frameworks/fastai: ./integrations/fastai/README.md
  frameworks/fastai-example: ./integrations/fastai.md
  frameworks/jax-example: ./library/example-projects/jax.md
  frameworks/keras: ./library/frameworks/keras.md
  frameworks/keras-example: ./library/example-projects/keras.md
  frameworks/numpy-example: ./library/example-projects/numpy.md
  frameworks/pytorch: ./library/frameworks/pytorch.md
  frameworks/pytorch-example: ./library/example-projects/pytorch.md
  frameworks/scikit: ./library/frameworks/scikit.md
  frameworks/scikit-example: ./library/example-projects/scikit.md
  frameworks/tensorflow: ./library/frameworks/tensorflow.md
  frameworks/tensorflow-example: ./library/example-projects/tensorflow.md
  frameworks/xgboost: ./library/frameworks/xgboost.md
  frameworks/xgboost-example: ./library/example-projects/xgboost.md
  getting-started: ./quickstart.md
  huggingface: ./integrations/huggingface.md
  java: ./ref/java/README.md
  java/wandbrun-builder: ./ref/java/wandbrun-builder.md
  java/wandbrun: ./ref/java/wandbrun.md
  library/advanced: ./guides/README.md
  library/advanced/grouping: ./library/grouping.md
  library/advanced/resuming: ./library/resuming.md
  library/advanced/security: ./library/security.md
  library/advanced/limits: ./library/limits.md
  library/api: ./ref/export-api/README.md
  library/api/examples: ./ref/export-api/examples.md
  library/reference: ./ref/README.md
  library/reference/wandb_api: ./ref/api.md
  library/reference/keras: ./ref/keras.md
  library/reference/data_types: ./ref/data-types.md
  library/reference/fastai: ./integrations/fastai/README.md
  library/sweeps: ./sweeps/overview.md
  library/sweeps/configuration: ./sweeps/configuration.md
  library/sweeps/advanced: ./sweeps/ray-tune.md
  library/sweeps/local-controller: ./sweeps/local-controller.md
  library/sweeps/python-api: ./sweeps/python-api.md
  library/example-projects: ./examples.md
  overview/company-faq: ./overview/company-faq.md
  overview/getting-help: ./overview/getting-help.md
  overview/overview: ./overview.md
  overview/technical-faq: ./overview/technical-faq.md
  sweeps/local: ./sweeps/local-controller.md
  sweeps/python: ./sweeps/python-api.md
  wandb/config: ./library/python/config.md
  wandb/init: ./library/python/init.md
  wandb/log: ./library/python/log.md
  wandb/restore: ./library/python/restore.md
  wandb/save: ./library/python/save.md
  library/integrations/pytorch: ./integrations/pytorch.md
  library/integrations/keras: ./integrations/keras.md
  library/integrations/tensorflow: ./integrations/tensorflow.md
  library/integrations/scikit: ./integrations/scikit.md
  library/integrations/pytorch: ./integrations/pytorch.md
  library/integrations/fastai: ./integrations/fastai/README.md
  library/integrations/fastai/fastai: ./integrations/fastai/v1.md
  library/integrations/xgboost: ./integrations/xgboost.md
  library/integrations/lightgbm: ./integrations/lightgbm.md
  library/integrations/huggingface: ./integrations/huggingface.md
  library/integrations/tensorboard: ./integrations/tensorboard.md
  library/integrations/sagemaker: ./integrations/sagemaker.md
  library/integrations/lightning: ./integrations/lightning.md
  library/integrations/ignite: ./integrations/ignite.md
  library/integrations/kubeflow: ./integrations/kubeflow.md
  library/integrations/docker: ./integrations/docker.md
  library/integrations/jupyter: ./integrations/jupyter.md
  library/integrations/mlflow: ./integrations/mlflow.md
  library/integrations/databricks: ./integrations/databricks.md
  library/integrations/ray-tune: ./integrations/ray-tune.md
  library/integrations/catalyst: ./integrations/catalyst.md
  library/integrations/skorch: ./integrations/skorch.md
  library/integrations/simpletransformers: ./integrations/simpletransformers.md
  library/integrations/openai-gym: ./integrations/openai-gym.md
  library/integrations/numpy: ./integrations/numpy.md
  library/integrations/jax: ./integrations/jax.md
